### ISSUE TITLE
Upgrade  exegesis  package to 3.0.1 due to ajv upgrade side effects.

### ISSUE THREAD

**Issue by acotty** [exegesis-js/exegesis-express#51]
Due to issues with exegesis 3.0.0 outlined in https://github.com/exegesis-js/exegesis/issues/262 , could the exegesis  package be upgraded to 3.01 and release a new version of exegesis-express be released.

Thanks.

**Comment by jwalton** [comment]
There should be no need for a new version of exegesis-express.  Since we haven’t changed the major version between 3.0.0 and 3.0.1, installing windows exegesis-express should pick up the latest exegesis.  If you’ve already installed the latest exegesis-express, your package-lock.json file (or your yarn lock file) controls which version of exegesis will be used.  You can delete your lock file, or ‘npm upgrade —depth 1 exegesis’ if you want to just upgrade exegesis (I’m typing this on my phone, and my phone keeps turning two dashes into an emdash, so don’t copy-paste that. :P)

**Comment by acotty** [comment]
I blew the lockfile away and regenerated it and it worked.  Thanks.

**Comment by jwalton** [comment]
Another way to do this if you run into a particularly stubborn dependency is to ‘npm install exegesis && npm uninstall exegesis’.  :P
